version: "3.9"

services:
  web:
    build: .
    container_name: p13-container
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # mount source code for live reload
      - /app/staticfiles