services:
  web:
    image: zolatso/p13-image:latest
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/staticfiles
    ports:
      - "8000:8000"