services:
  web:
    build:
      context: ..
      dockerfile: docker/dev/Dockerfile
    env_file:
      - .env.dev
    volumes:
      - ../:/app
      - /app/staticfiles
    ports:
      - "8000:8000"