# Generated by Django 4.2.24 on 2025-09-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RemoveField(model_name='letting',name='address',),],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='Address',),], 
            database_operations=[migrations.AlterModelTable(name='Address', table='lettings_address',),],),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='Letting',),], 
            database_operations=[migrations.AlterModelTable(name='Letting', table='lettings_letting',),],),
    ]
