# Generated by Django 4.2.24 on 2025-09-11 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "oc_lettings_site",
            "0002_remove_letting_address_delete_address_delete_letting",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Profile",
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name="Profile",
                    table="profiles_profile",
                ),
            ],
        ),
    ]
